### PR TITLE
Add classes to override default settings banner style

### PR DESCRIPTION
**Pull request by iwolfisberg**
### 💬 Description
Add classes to override default settings banner style.
Update READ.me accordingly.

- [x] Update the "Unreleased" section of the `CHANGELOG.md` with [chan](https://github.com/geut/chan/tree/main/packages/chan)

### CODE REVIEW

**Comment by Yago** [comment]
I don't know about those classes 🤔 Before approving or not, I drop this question here : **are style target classes are that useful to override Leckerli default design ?**

I had to do this work on Cardis where it doesn't look like Leckerli at all: 

CleanShot 2023-10-10 at 15 26 32

First, I used the existing target classes, but quickly, I saw that like this PR propose, it misses a lot of other selectors. So I manage to select the elements I want to override under `#lkrl-wrapper` and maybe it's not the nicest CSS I wrote (especially for the ID usage part), but it works without adding more classes.

[See the “result” for yourself](https://github.com/antistatique/cardis-website/blob/dev/src/styles/leckerli.css)

So now, are we adding more classes to select every bit of Leckerli UI or are we removing all this class approch to simply use CSS selectors under `#lkrl-wrapper` ?

I personally don't have a strong opinion on this one, so I really want all of your feedbacks @iwolfisberg @yannlugrin and @gido 🤗

**Comment by iwolfisberg** [comment]
@Yago I'm fine doing it your way, I'm just not sure about the durability of this approach but we can go on that way.
But from what I see in Cardis CSS, you have used some of the classes I have added for overriding the style (`.banner-btns` in particular). If I remove all of the classes, can you still achieve the styling of the banner ?

**Comment by gido** [comment]
My two cents: I prefer to have explicit css classes (what is proposed in this PR). This way, this is somehow part of the API.

CSS selector on the project linked by @Yago looks a bit hacky:

 * `#lkrl-wrapper div[class*="fixed"]`
 * `#lkrl-wrapper button[class*="bg-primary"][class*="rounded "]`
 * `#lkrl-wrapper div[class*="fixed"] > div:not(.banner-btns)`
 
 I'm not sure if this PR will solve all we need for a custom design but if it help I'm in favor of this PR

**Review by Yago — APPROVED** [review]
Ok, so let's do it this way 😉

**Pull request merged**
